parameters:
#    ssp_proyectos.example.class: SSP\ProyectosBundle\Example

services:
#    ssp_proyectos.example:
#        class: %ssp_proyectos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
